Repository Arquisoft/wichat_es4a, pull requests merged in 2025-04, with the labels that each got.

#121 Cambio de Librería react-router-dom -> react-router + Mejora en Navbar
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.js
  webapp/src/components/AddUser.js
  webapp/src/components/Login.js
  webapp/src/components/NavBar.js
  webapp/src/components/game/Game.js
  webapp/src/components/game/GameResults.js
  webapp/src/components/home/Configuration.js
  webapp/src/components/routers/AppRouter.js
  webapp/src/components/routers/AuthRoute.js
  webapp/src/components/userMenu/UserProfile.js
Labels: front-end

#128 Tests de los componentes NavBar, Home, Rules y Configuration
  webapp/src/components/AddUser.test.js
  webapp/src/components/Login.test.js
  webapp/src/components/NavBar.js
  webapp/src/components/NavBar.test.js
  webapp/src/components/Rules.test.js
  webapp/src/components/home/Configuration.js
  webapp/src/components/home/Configuration.test.js
  webapp/src/components/home/Home.test.js
Labels: front-end, testing

#127 Actualización del Punto 3
  docs/images/03-Diagrama-Despliegue.png
  docs/images/diagrama-despliegue.png
  docs/src/03_context_and_scope.adoc
Labels: documentation

#130 Tests microservicio questionservice
  gatewayservice/gateway-service.js
  questionservice/babel.config.js
  questionservice/jest.config.js
  questionservice/package-lock.json
  questionservice/package.json
  questionservice/question-service.js
  questionservice/question-service.test.js
  questionservice/question_template.json
Labels: back-end

#131 Tests de Componentes
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/game/GameResults.test.js
  webapp/src/components/gameHistory/GameHistoryButton.test.js
  webapp/src/components/routers/AppRouter.js
  webapp/src/components/userMenu/EditUser.test.js
  webapp/src/components/userMenu/UserProfile.js
  webapp/src/i18n/i18next.js
  webapp/src/setupTests.js
Labels: front-end, testing

#140 Fix de Varios Usuarios con Mismo Username + Tests de Componentes
  users/userservice/user-service.js
  webapp/public/locales/en/translation.json
  webapp/public/locales/es/translation.json
  webapp/src/components/AddUser.js
  webapp/src/components/AddUser.test.js
  webapp/src/components/Login.test.js
  webapp/src/components/contextProviders/GameConfigProvider.js
  webapp/src/components/game/AnswerButton.js
  webapp/src/components/game/Game.js
  webapp/src/components/game/Game.test.js
  webapp/src/components/game/LLMChat.js
  webapp/src/components/game/LLMChat.test.js
Labels: testing

#151 Back andrea
  gameservice/Dockerfile
  gameservice/db/mongo/Connection.js
  gameservice/game-service.js
  gameservice/game/GameManager.js
  gameservice/game/QuestionAsk.js
  gameservice/gameTesttest.test.js
  gameservice/jest.config.js
  gameservice/models/Question.js
  gameservice/models/game_played.js
  gameservice/models/index.js
  gameservice/package-lock.json
  gameservice/package.json
  gatewayservice/gateway-service-utils.js
  gatewayservice/gateway-service.js
  gatewayservice/general.js
  questionservice/Dockerfile
  questionservice/WikiData-ejemplo-aitor.js
  questionservice/package-lock.json
  questionservice/package.json
  questionservice/question.js
  questionservice/question_template.json
  testing/artillery/test-edit.yml
  testing/artillery/test-game-new-getQuestion.yml
Labels: bug, back-end, db, testing, test

#152 Tests de Carga y más
  deploy/terraform/mainv2.tf
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  llmservice/llm-service-utils.js
  llmservice/llm-service.js
  llmservice/llm-service.test.js
  testing/artillery/processor.js
  testing/artillery/test-adduser.yml
  testing/artillery/test-endAndSaveGame.yml
  testing/artillery/test-home.yml
  testing/artillery/test-login.yml
  webapp/src/components/game/LLMChat.js
Labels: back-end, code-review, llm, test

#155 Documentación microservicio donationservice
  docs/src/01_introduction_and_goals.adoc
  docs/src/02_architecture_constraints.adoc
  docs/src/03_context_and_scope.adoc
  docs/src/05_building_block_view.adoc
  docs/src/07_deployment_view.adoc
  docs/src/12_glossary.adoc
Labels: documentation

#162 Tests unitarios añadidos en gateway-service.test.js
  gatewayservice/gateway-service.test.js
Labels: test

#163 tests en "gatewayservice" para el nuevo microservicio de donaciones
  gatewayservice/gateway-service.test.js
Labels: back-end, test

#165 Nuevo Sistema de Donaciones + Testing
  .github/workflows/release.yml
  .vscode/settings.json
  docker-compose.yml
  donationservice/Dockerfile
  donationservice/donate.js
  donationservice/donate.test.js
  donationservice/package-lock.json
  donationservice/package.json
  donationservice/public/images/logo.ico
  donationservice/public/images/logo.png
  gameservice/game-service.js
  gameservice/game/QuestionAsk.js
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  package-lock.json
  package.json
  sonar-project.properties
  testing/artillery/test-game-question.yml
  testing/artillery/test-question-new.yml
  webapp/e2e/features/change-password.feature
  webapp/e2e/features/game.feature
  webapp/e2e/steps/change-password.steps.js
  webapp/e2e/steps/game.steps.js
  webapp/public/locales/en/translation.json
  webapp/public/locales/es/translation.json
  webapp/src/components/NavBar.js
  webapp/src/components/Rules.js
  webapp/src/components/contextProviders/GameConfigProvider.js
  webapp/src/components/game/Game.js
  webapp/src/components/gameHistory/GameHistoryButton.js
  webapp/src/components/home/Configuration.js
  webapp/src/components/home/Home.js
  webapp/src/components/nav.css
  webapp/src/components/routers/NotAuthorizedRouter.js
  webapp/src/components/userMenu/EditUser.js
  webapp/src/components/userMenu/UserProfile.js
  webapp/src/index.js
  webapp/src/services/DonationService.js
Labels: enhancement, testing

#167 Tests de Routers de Autorización
  webapp/src/components/routers/NotAuthorizedRouter.test.js
  webapp/src/components/routers/PrivateRouter.test.js
Labels: testing

#157 Actualización Documentación con Nuevo microservicio donation
  docs/images/03-Diagrama-Despliegue.png
  docs/images/building_block_view1.png
  docs/images/building_block_view2.png
  docs/images/building_block_view3.png
  docs/images/contexto-de-negocio.png
  docs/images/vista-de-despliegue-nivel-1.png
  docs/images/vista-de-despliegue-nivel-2.png
  docs/src/03_context_and_scope.adoc
  docs/src/05_building_block_view.adoc
  docs/src/07_deployment_view.adoc
  docs/src/12_glossary.adoc
Labels: documentation
