Repository Arquisoft/wichat_es4a, pull requests merged in 2025-03, with the labels that each got.

#48 Mix javier
  facade/QuestionGame.js
  gatewayservice/gateway-service.js
  webapp/src/components/game/Game.js
  webapp/src/components/game/Timer.js
  webapp/src/components/game/game.css
  webapp/src/services/GameService.js
Labels: enhancement

#50 Front javier
  webapp/src/components/game/Game.js
  webapp/src/components/game/GameConfigProvider.js
  webapp/src/components/home/Configuration.js
  webapp/src/components/home/Home.js
  webapp/src/components/routers/AppRouter.js
Labels: enhancement

#68 Nuevo diseño de interfaces de Login y AddUser
  webapp/public/images/logo.png
  webapp/public/locales/en/translation.json
  webapp/public/locales/es/translation.json
  webapp/src/components/AddUser.js
  webapp/src/components/Login.js
  webapp/src/components/NavBar.js
Labels: front-end

#70 Acordeón de Preguntas
  webapp/src/components/game/Game.js
  webapp/src/components/gameHistory/QuestionAccordion.js
  webapp/src/components/routers/AppRouter.js
Labels: front-end

#66 Microservicio Juego
  db/Connection.js
  db/crud.js
  db/index.js
  db/initDB.js
  db/package-lock.json
  db/package.json
  facade/GameSession.js
  facade/QuestionGame.js
  facade/testGame.js
  game_service/db/mongo/Connection.js
  game_service/game.js
  game_service/game/GameService.js
  game_service/game/QuestionAsk.js
  game_service/game/questionService.js
  game_service/models/Question.js
  game_service/models/game_played.js
  game_service/models/index.js
  game_service/models/user.js
  game_service/package-lock.json
  game_service/package.json
  gatewayservice/gateway-service.js
  gatewayservice/package.json
  llmservice/llm-service.js
  package-lock.json
  repository/GameRepository.js
  users/authservice/auth-service.js
Labels: back-end, code-review, db

#80 Nuevo Campo Confirm Password + Validación en el Servidor
  users/userservice/user-service.js
  webapp/public/locales/en/translation.json
  webapp/public/locales/es/translation.json
  webapp/src/components/AddUser.js
  webapp/src/components/NavBar.js
  webapp/src/components/rules.css
  webapp/src/components/userMenu/EditUser.js
  webapp/src/components/userMenu/UserProfile.js
Labels: front-end

#86 Implementación de Protección contra Ataques de Fuerza Bruta en LogIn
  users/authservice/auth-service.js
  users/authservice/package-lock.json
  users/authservice/package.json
  webapp/public/locales/en/translation.json
  webapp/public/locales/es/translation.json
  webapp/src/components/Login.js
  webapp/src/components/contextProviders/AuthContext.js
  webapp/src/components/game/AnswerButton.js
  webapp/src/components/game/Game.js
  webapp/src/components/game/Timer.js
Labels: back-end, front-end, security

#87 Documentación Punto 7: Vista de Despliegue
  docs/images/contexto-de-negocio.png
  docs/images/logo.png
  docs/images/vista-de-despliegue-nivel-1.png
  docs/images/vista-de-despliegue-nivel-2.png
  docs/index.adoc
  docs/src/03_context_and_scope.adoc
  docs/src/07_deployment_view.adoc
Labels: documentation

#99 Paso de Información de Partida al Backend
  webapp/src/components/game/Game.js
  webapp/src/services/GameService.js
Labels: front-end

#101 Implementación de Cambio de Contraseña + Fix en envío de Session Token en POST
  gatewayservice/gateway-service.js
  gatewayservice/package-lock.json
  gatewayservice/package.json
  users/userservice/user-service.js
  webapp/src/components/game/Game.js
  webapp/src/components/userMenu/EditUser.js
  webapp/src/services/GameService.js
  webapp/src/services/UserProfileService.js
Labels: enhancement, back-end, front-end

#91 Documentación punto 9
  docs/src/09_architecture_decisions.adoc
Labels: documentation

#98 Implementación Puntos 11 y 12 de la Documentación
  docs/src/01_introduction_and_goals.html
  docs/src/11_technical_risks.adoc
  docs/src/12_glossary.adoc
Labels: documentation
