Repository Arquisoft/wichat_es4a, pull requests merged in 2025-05, with the labels that each got.

#172 Documentar donationservice, añadir nuevos idiomas y corregir gráfico de sectores
  donationservice/donate.js
  gameservice/game-service.test.js
  gameservice/game/GameManager.js
  questionservice/question_template.json
  webapp/public/locales/de/translation.json
  webapp/public/locales/en/translation.json
  webapp/public/locales/es/translation.json
  webapp/public/locales/fr/translation.json
  webapp/public/locales/it/translation.json
  webapp/src/components/NavBar.js
  webapp/src/components/game/ResultSectorChart.js
Labels: documentation, back-end, front-end, i18n

#173 Eliminación de dependencias que no se usan de package.json base
  package-lock.json
  package.json
Labels: code-review

#174 Mejoras en la adaptabilidad, fix del bug del idioma, fix del bug del scroll en imágenes grandes y test nuevos para idiomas nuevos
  webapp/src/components/NavBar.test.js
  webapp/src/components/game/LLMChat.js
  webapp/src/components/game/ResultSectorChart.js
  webapp/src/components/game/game.css
  webapp/src/i18n/i18next.js
Labels: bug, front-end

#178 Mejora en las Imágenes de las Preguntas
  webapp/src/components/game/Game.js
  webapp/src/components/game/QuestionImage.js
  webapp/src/components/game/QuestionImage.test.js
  webapp/src/components/game/game.css
  webapp/src/components/gameHistory/QuestionAccordion.js
Labels: front-end

#180 Fix Documentación
  docs/images/03-Diagrama-Despliegue.png
  docs/images/07-Diagrama-Despliegue-Nivel-1.png
  docs/images/07-Diagrama-Despliegue-Nivel-2.png
  docs/src/03_context_and_scope.adoc
  docs/src/07_deployment_view.adoc
Labels: documentation
